"use client";
import type {Snapshot} from "../lib/types";
import {roadmap,initialHistory} from "../lib/roadmap";
const date=(value:string)=>new Date(value.length===10?value+"T12:00:00Z":value).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
const number=(value:number)=>value.toLocaleString("en-US");
export default function Updates({snapshot}:{snapshot:Snapshot}) {
  const operations=snapshot.operations;
  const sessions=operations?.recentRuns??[];
  const history=(operations?.contentHistory??[]).filter(h=>h.kind==="content"&&h.at.slice(0,10)>"2026-10-06");
  return <section className="updates-page" aria-labelledby="updates-title">
    <div className="page-heading"><div className="eyebrow">TRANSPARENCY / DELIVERY</div><h1 id="updates-title">What changed.<br/>What comes next.</h1><p>Content additions, operating activity and the next steps in Ripple’s development. Dates describe different kinds of work; a source check does not advance every claim’s verification date.</p></div>
    <div className="updates-overview"><article><span>Research edition</span><strong>{number(snapshot.records.length)} assessment records</strong><p>{snapshot.candidates.length} investigations in the current view. Coverage is partial.</p></article><article><span>Latest source check</span><strong>{snapshot.lastRun?date(snapshot.lastRun):"Not run"}</strong><p>Individual findings retain their own supporting evidence and verification dates.</p></article><article><span>Latest assessment</span><strong>{snapshot.lastAssessmentAt?date(snapshot.lastAssessmentAt):"Not run"}</strong><p>Rechecks and additions are recorded separately below.</p></article></div>
    <section className="updates-section"><h2>Content and feature history</h2><p>Actual additions and material corrections. Routine no-change checks appear in operating activity.</p><ol className="updates-timeline">{[...history.map(h=>({id:h.id,at:h.at,title:"Research content updated",summary:h.summary})),...initialHistory.slice().reverse()].map(h=><li key={h.id}><time dateTime={h.at}>{date(h.at)}</time><div><h3>{h.title}</h3><p>{h.summary}</p></div></li>)}</ol></section>
    <section className="updates-section"><h2>Upcoming rollout</h2><p>Target dates, not guaranteed release dates. Each update depends on its validation and budget check. A target passing does not change a planned item to delivered.</p><div className="roadmap-list">{roadmap.map(item=><article key={item.id} className="roadmap-card"><div className="roadmap-meta"><time dateTime={item.target}>{date(item.target)}</time><span className={"roadmap-status "+item.status}>{item.status==="available"?"Available":"Planned"}</span></div><h3>{item.title}</h3><p>{item.scope}</p><details><summary>What must be verified</summary><p>{item.gate}</p></details></article>)}</div></section>
    <section className="updates-section"><h2>Operating activity and limits</h2><p>Measured research operations only. No visitor selections, watchlists or customer inventory are collected.</p>{operations?<><dl className="operating-grid"><div><dt>Automated source requests today</dt><dd>{number(operations.requestsToday)} / {operations.policy.dailyRequests}</dd></div><div><dt>Research sessions admitted today</dt><dd>{operations.researchSessionsToday} / {operations.policy.dailyInvestigations}</dd></div><div><dt>Research time reserved today</dt><dd>{operations.researchReservedMinutes} / {operations.policy.dailyResearchMinutes} minutes</dd></div><div><dt>Durable investigation queue</dt><dd>{operations.queue.total} <small>{operations.queue.pending} pending · {operations.queue.waiting} waiting · {operations.queue.inProgress} in progress</small></dd></div></dl><p className="operating-note">Daily counters reset at 00:00 UTC. Each admitted research session has a {operations.policy.researchSessionMinutes}-minute window. Collection retries count toward the request cap; exhausted work is deferred. Elapsed collection time is not model reasoning time.</p><div className="investigation-table"><table><caption>Recent collection and assessment runs</caption><thead><tr><th>Date</th><th>Stage</th><th>Requests</th><th>Elapsed</th><th>Retries</th><th>Deferred</th><th>New leads</th></tr></thead><tbody>{sessions.slice(-10).reverse().map(r=><tr key={r.kind+r.at}><td><time dateTime={r.at}>{date(r.at)}</time></td><td>{r.kind}</td><td>{r.requests}</td><td>{(r.durationMs/1000).toFixed(1)}s</td><td>{r.retries}</td><td>{r.deferred}</td><td>{r.candidatesAdded}</td></tr>)}</tbody></table></div><p className="operating-note">{operations.cost.note} Run measurements began October 7; earlier runs have no reconstructed usage figures.</p></>:<div className="investigation-gap">Operating measurements have not been loaded. Historical research remains available; no current usage or queue count is inferred.</div>}
    <details className="operating-history"><summary>Recorded assessment history</summary><ul>{(snapshot.assessmentRuns??[]).slice().reverse().map(r=><li key={r.id}><time dateTime={r.at}>{date(r.at)}</time>: {r.claimChecks} scoped claims checked, {r.addedRecords} added, {r.failures} evidence retrieval failures.</li>)}</ul></details></section>
    <section className="updates-section updates-method"><h2>How this page stays accountable</h2><p>Content history records additions and corrections. Source checks record retrieval and change detection. Claim dates record the original evidence review. Research sessions record unresolved questions and next actions. None of those measures establishes comprehensive Cisco coverage.</p><p>The pilot stays at <a href="/ripple">VersionCompass.com/ripple</a>. The research service is read-only here, with local context kept in your browser. Main-site navigation is a later rollout decision.</p><a className="text-button" href="https://github.com/LeiterConsulting/splunk-version-value-explorer/tree/main/tools/ripple" target="_blank" rel="noopener noreferrer">View the public interface source ↗</a></section>
  </section>;
}
