export type Verdict = "affected" | "not_affected" | "review";
export type Rule = { branch: string; from: string; through: string; fixed: string };
export type Assessment = {
  id: string; cve: string; component: string; title: string; product: string;
  family: string; severity: "Critical" | "High" | "Medium" | "Low" | "Informational";
  verdict: Verdict; relationship: "embedded" | "protocol" | "integration" | "host";
  scope: string; condition: string; action: string; sourceId: string; section: string;
  verifiedAt: string; rules?: Rule[]; feature?: string; reviewRequired?: boolean;
  kev?: boolean; kevDate?: string; rationale: string;
  evidence?: Evidence; relatedEvidence?: Evidence[];
};
export type Evidence = { id: string; name: string; url: string; section: string; checkedAt: string; hash?: string };
export type ProductScope = { product: string; branch: string; affected: string; fixed: string; component?: string };
export type PackageGroup = { component: string; cves: string[]; severity: string; remedy: string; note: string };
export type Investigation = {
  state: "mapped" | "needs_evidence" | "related_first_party" | "unavailable";
  assessedAt: string; evidence: Evidence[]; summary: string; gaps: string[]; nextAction: string;
  products: ProductScope[]; packages: PackageGroup[]; assessmentIds: string[];
  priority: "high" | "normal"; previousState?: Investigation["state"];
};
export type AssessmentRun = { id: string; at: string; investigationsChecked: number; mapped: number;
  needsEvidence: number; relatedFirstParty: number; failures: number; claimChecks: number; addedRecords: number };
export type SourceCheck = { id: string; name: string; url: string; checkedAt: string;
  outcome: "ok" | "changed" | "unavailable" | "deferred"; hash?: string; message: string };
export type Candidate = { id: string; title: string; url: string; origin: string;
  cves: string[]; discoveredAt: string; publishedAt?: string; kev?: boolean; investigation?: Investigation;
  queue?: {state:"pending"|"waiting"|"in_progress"; nextReviewAt:string; lastResearchAt?:string; reason:string} };
export type RunMetrics = {kind:"refresh"|"assessment"; at:string; durationMs:number; requests:number;
  receivedBytes:number; retries:number; deferred:number; candidatesAdded:number; queueSize:number; oldestPendingAt:string|null; snapshotBytes:number};
export type OperatingData = {policy:{dailyRequests:number; dailyInvestigations:number; researchSessionMinutes:number; dailyResearchMinutes:number};
  day:string; requestsToday:number; receivedBytesToday:number; researchSessionsToday:number; researchReservedMinutes:number;
  queue:{total:number; pending:number; waiting:number; inProgress:number; oldestPendingAt:string|null};
  recentRuns:RunMetrics[]; contentHistory:{id:string; at:string; kind:string; summary:string; added:number; updated:number}[];
  cost:{status:"not_metered"; note:string}};
export type Snapshot = { schemaVersion: 1; records: Assessment[]; candidates: Candidate[];
  checks: SourceCheck[]; lastRun: string | null; storage: "baseline" | "persistent";
  updateStatus: "not_run" | "complete" | "partial"; runs: number;
  lastAssessmentAt?: string; assessmentRuns?: AssessmentRun[]; operations?:OperatingData };
export type Selection = { version?: string; feature?: "unknown" | "enabled" | "disabled" };
