const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const window={};vm.runInNewContext(fs.readFileSync('dist/content-updates.js','utf8'),{window});const b=window.VersionCompassUpdates;
test('change badges expire after two material cycles, not elapsed days',()=>{const e={cycle:5};assert(!b.active(e,4));assert(b.active(e,5));assert(b.active(e,6));assert(!b.active(e,7));assert(!b.active(e,100));});
test('badges are explicit, qualified and printable with evidence',()=>{assert.equal(b.html('unknown'), '');for(const [key,e] of Object.entries(b.entries)){assert(e.source.startsWith('https://'));assert.match(e.date,/^\d{4}-\d{2}-\d{2}$/);const h=b.html(key,{milestone:e.milestones?.[0]});if(!b.active(e)){assert.equal(h,'');continue;}assert(h.includes(e.source));assert(h.includes('content-change-print'));assert(h.includes('aria-label'));assert(h.includes(e.version));}const deprecation=b.entries['technical:observability:Browser RUM navigation configuration'];assert.match(deprecation.detail,/remains functional/);assert.match(deprecation.detail,/not removal/);});
test('the sixteenth factual cycle restores held changes alongside current environment changes and retains prior change history',()=>{assert.equal(b.policy.currentCycle,16);assert(!b.active(b.entries['feature:observability:Browser RUM 3.2']));const maintenance=b.entries['technical:platform:Enterprise 10.4 maintenance target'];assert(!b.active(maintenance));assert.equal(maintenance.kind,'updated');const detector=b.entries['feature:observability:Detector Optimization'];assert(!b.active(detector));assert.equal(detector.kind,'new');const python=b.entries['feature:observability:Python instrumentation 2.13'];assert(!b.active(python));for(const key of ['environment:s3-moderate','environment:machine-data-lake-aws','environment:machine-data-lake-gov','environment:machine-data-lake-gcp','environment:machine-data-lake-azure']){const e=b.entries[key];assert.equal(e.cycle,15);assert(b.active(e));assert.match(e.note,/2026\/10\/2026-10-09\.md/);}for(const key of ['compatibility:es:cloud-current','compatibility:itsi:cloud-current','technical:forwarders:10.6 receiver compatibility','technical:forwarders:Cloud 10.6 receiver compatibility','technical:platform:Cloud 10.6 publication versus stack availability']){const e=b.entries[key];assert.equal(e.cycle,14);assert(!b.active(e));assert.match(e.note,/2026\/10\/2026-10-07\.md/);}const offerings=b.entries['environment:es-fr-m-offering'];assert(!b.active(offerings));assert.equal(offerings.cycle,13);const kv=b.entries['technical:platform:KV Store database engine'];assert(!b.active(kv));assert.equal(b.entries['technical-history:platform:KV Store database engine:2026-10-01-cycle5'].recordKey,'technical:platform:KV Store database engine');const prior=b.entries['technical-history:platform:Enterprise 10.4 maintenance target:2026-09-26'];assert.equal(prior.recordKey,'technical:platform:Enterprise 10.4 maintenance target');assert.match(prior.note,/2026-09-26\.md/);});

test('10.6 technical badges never label older or Cloud records',()=>{for(const key of ['technical:platform:KV Store database engine','technical:platform:Legacy TLS protocols']){assert.equal(b.html(key,{milestone:'Enterprise 10.4'}),'');assert.equal(b.html(key,{milestone:'Cloud 10.6'}),'');assert(b.entries[key].milestones.includes('Enterprise 10.6'));assert.equal(Boolean(b.html(key,{milestone:'Enterprise 10.6'})),b.active(b.entries[key]));}});
test('cycle thirteen offering badges expire after two material cycles but retain provenance',()=>{for(const key of ['environment:es-fr-m-offering','environment:es-fr-h-offering','environment:itsi-fr-m-offering','environment:itsi-fr-h-offering','product:soar:fedramp-moderate-offering']){const e=b.entries[key];assert(e);assert.equal(e.cycle,13);assert(!b.active(e));assert.match(e.detail,/separate|scope/);assert.equal(b.html(key),'');}});

test("restored release markers share one new material cycle",()=>{for(const key of ["technical:platform:Enterprise 9.4 October security floor", "technical:platform:Enterprise 10.0 October security floor", "technical:platform:Enterprise 10.2 October security floor", "technical:platform:Enterprise 10.4 October security floor", "feature:observability:Collector 0.162 migration controls", "feature:observability:Kubernetes chart 0.162", "technical:observability:Collector 0.162 retired receivers and processor names", "technical:observability:Collector Windows service identity", "technical:observability:Kubernetes chart 0.162 package baseline", "technical:observability:Python instrumentation 2.13 patch baseline", "product:soar:6.4.1.361-floor"]){const e=b.entries[key];assert.equal(e.cycle,16);assert(b.active(e));assert.match(e.note,/2026\/10\/2026-10-09\.md/);}});
