const { test } = require('node:test');
const assert = require('node:assert/strict');
async function fixture(kind = 'Compatibility rule / historical scope') {
  const m = await import('../worker/publication-core.mjs');
  const engine = 'engine-' + 'a'.repeat(20), commit = 'b'.repeat(40);
  const globals = { SPLUNK_DATA: {}, VersionCompassEnvironmentData: {}, VersionCompassEditions: {}, VersionCompassForwarderData: {}, VersionCompassSOARData: {} };
  const catalog = { schemaVersion: 1, records: [{ id: 'vc-' + 'c'.repeat(20), kind, dataset: 'platform', scope: {}, evidence: [], verification: { date: null, outcome: 'Claim verification not recorded' }, payload: { title: 'Synthetic schema fixture' } }] };
  const digest = await m.sha256({ schemaVersion: 1, globals, catalog });
  const bundle = { manifest: { schemaVersion: 1, revision: 'content-' + (await m.sha256({ digest, engineRevision: engine })).slice(0, 24), digest, engineRevision: engine, datasetHashes: Object.fromEntries(m.DATASETS.map(id => [id, 'd'.repeat(64)])), recordCount: 1, provenance: 'Test', verificationPolicy: 'Preserve dates', phase: 'test' }, globals, catalog };
  return { m, engine, candidate: { repository: m.REPOSITORY, commit, bundle } };
}
test('existing schema permits free-form record kind strings without rewriting them', async () => {
  const { m, engine, candidate } = await fixture();
  assert.deepEqual(await m.validateBundle(candidate.bundle, engine), candidate.bundle);
});
test('record kinds still reject empty and non-string values', async () => {
  for (const kind of ['', '  ', 1, null, {}, 'x'.repeat(201)]) {
    const { m, engine, candidate } = await fixture(kind);
    await assert.rejects(m.validateBundle(candidate.bundle, engine), /record kind/);
  }
});
test('provenance recognizes GitHub autogenerated Run step names but never skipped steps', async () => {
  const { m, engine, candidate } = await fixture();
  let skip = false;
  const fetcher = async url => {
    let value;
    if (url.includes('/compare/')) value = { status: 'identical', base_commit: { sha: candidate.commit }, merge_base_commit: { sha: candidate.commit } };
    else if (url.includes('/actions/runs?')) value = { workflow_runs: [{ id: 99, head_sha: candidate.commit, head_branch: 'main', event: 'push', path: '.github/workflows/validate.yml', repository: { full_name: m.REPOSITORY }, status: 'completed', conclusion: 'success' }] };
    else if (url.includes('/jobs?')) value = { jobs: [{ name: 'validate', status: 'completed', conclusion: 'success', steps: m.REQUIRED_STEPS.map(name => ({ name: 'Run ' + name, status: 'completed', conclusion: skip && name.includes('build-worker') ? 'skipped' : 'success' })) }] };
    else value = url.endsWith('/content/publication.json') ? candidate.bundle.manifest : candidate.bundle;
    return new Response(JSON.stringify(value));
  };
  assert.equal((await m.verifyRepositoryPublication(candidate, { engineRevision: engine, fetcher })).provenance.workflowRun, 99);
  skip = true;
  await assert.rejects(m.verifyRepositoryPublication(candidate, { engineRevision: engine, fetcher }), /validation or build/);
});
